module.exports = {
    sheetSize: 37,
    groups: {
        Symbols: [ "watch", "iphone", "calling", "computer", "alarm_clock", "hourglass_flowing_sand", "hourglass", "camera", "video_camera", "movie_camera", "tv", "radio", "pager", "telephone_receiver", "phone", "fax", "minidisc", "floppy_disk", "cd", "dvd", "vhs", "battery", "electric_plug", "bulb", "flashlight", "satellite", "credit_card", "money_with_wings", "moneybag", "gem", "closed_umbrella", "pouch", "purse", "handbag", "briefcase", "school_satchel", "lipstick", "eyeglasses", "womans_hat", "sandal", "high_heel", "boot", "mans_shoe", "athletic_shoe", "bikini", "dress", "kimono", "womans_clothes", "shirt", "necktie", "jeans", "door", "shower", "bathtub", "toilet", "barber", "syringe", "pill", "microscope", "telescope", "crystal_ball", "wrench", "hocho", "nut_and_bolt", "hammer", "bomb", "smoking", "gun", "bookmark", "newspaper", "key", "email", "envelope_with_arrow", "incoming_envelope", "e-mail", "inbox_tray", "outbox_tray", "package", "postal_horn", "postbox", "mailbox_closed", "mailbox", "mailbox_with_mail", "mailbox_with_no_mail", "page_facing_up", "page_with_curl", "bookmark_tabs", "chart_with_upwards_trend", "chart_with_downwards_trend", "bar_chart", "date", "calendar", "low_brightness", "high_brightness", "scroll", "clipboard", "book", "notebook", "notebook_with_decorative_cover", "ledger", "closed_book", "green_book", "blue_book", "orange_book", "books", "card_index", "link", "paperclip", "pushpin", "scissors", "triangular_ruler", "round_pushpin", "straight_ruler", "triangular_flag_on_post", "file_folder", "open_file_folder", "black_nib", "pencil2", "memo", "lock_with_ink_pen", "closed_lock_with_key", "lock", "unlock", "mega", "loudspeaker", "speaker", "sound", "loud_sound", "mute", "zzz", "bell", "no_bell", "thought_balloon", "speech_balloon", "children_crossing", "mag", "mag_right", "no_entry_sign", "no_entry", "name_badge", "no_pedestrians", "do_not_litter", "no_bicycles", "non-potable_water", "no_mobile_phones", "underage", "accept", "ideograph_advantage", "white_flower", "secret", "congratulations", "u5408", "u6e80", "u7981", "u6709", "u7121", "u7533", "u55b6", "u6708", "u5272", "u7a7a", "sa", "koko", "u6307", "chart", "sparkle", "eight_spoked_asterisk", "negative_squared_cross_mark", "white_check_mark", "eight_pointed_black_star", "vibration_mode", "mobile_phone_off", "vs", "a", "b", "ab", "cl", "o2", "sos", "id", "parking", "wc", "cool", "free", "new", "ng", "ok", "up", "atm", "aries", "taurus", "gemini", "cancer", "leo", "virgo", "libra", "scorpius", "sagittarius", "capricorn", "aquarius", "pisces", "restroom", "mens", "womens", "baby_symbol", "wheelchair", "potable_water", "no_smoking", "put_litter_in_its_place", "arrow_forward", "arrow_backward", "arrow_up_small", "arrow_down_small", "fast_forward", "rewind", "arrow_double_up", "arrow_double_down", "arrow_right", "arrow_left", "arrow_up", "arrow_down", "arrow_upper_right", "arrow_lower_right", "arrow_lower_left", "arrow_upper_left", "arrow_up_down", "left_right_arrow", "arrows_counterclockwise", "arrow_right_hook", "leftwards_arrow_with_hook", "arrow_heading_up", "arrow_heading_down", "twisted_rightwards_arrows", "repeat", "repeat_one", "hash", "zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "keycap_ten", "1234", "abc", "abcd", "capital_abcd", "information_source", "signal_strength", "cinema", "symbols", "heavy_plus_sign", "heavy_minus_sign", "wavy_dash", "heavy_division_sign", "heavy_multiplication_x", "heavy_check_mark", "arrows_clockwise", "tm", "currency_exchange", "heavy_dollar_sign", "curly_loop", "loop", "part_alternation_mark", "exclamation", "question", "grey_exclamation", "grey_question", "bangbang", "interrobang", "x", "o", "100", "end", "back", "on", "top", "soon", "cyclone", "m", "ophiuchus", "six_pointed_star", "beginner", "trident", "warning", "hotsprings", "recycle", "anger", "diamond_shape_with_a_dot_inside", "spades", "clubs", "hearts", "diamonds", "ballot_box_with_check", "white_circle", "black_circle", "radio_button", "red_circle", "large_blue_circle", "small_red_triangle", "small_red_triangle_down", "small_orange_diamond", "small_blue_diamond", "large_orange_diamond", "large_blue_diamond", "black_small_square", "white_small_square", "black_large_square", "white_large_square", "black_medium_square", "white_medium_square", "black_medium_small_square", "white_medium_small_square", "black_square_button", "white_square_button", "clock1", "clock2", "clock3", "clock4", "clock5", "clock6", "clock7", "clock8", "clock9", "clock10", "clock11", "clock12", "clock130", "clock230", "clock330", "clock430", "clock530", "clock630", "clock730", "clock830", "clock930", "clock1030", "clock1130", "clock1230" ],
        Nature: [ "seedling", "evergreen_tree", "deciduous_tree", "palm_tree", "cactus", "tulip", "cherry_blossom", "rose", "hibiscus", "sunflower", "blossom", "bouquet", "ear_of_rice", "herb", "four_leaf_clover", "maple_leaf", "fallen_leaf", "leaves", "mushroom", "chestnut", "rat", "mouse2", "mouse", "hamster", "ox", "water_buffalo", "cow2", "cow", "tiger2", "leopard", "tiger", "rabbit2", "rabbit", "cat2", "cat", "racehorse", "horse", "ram", "sheep", "goat", "rooster", "chicken", "baby_chick", "hatching_chick", "hatched_chick", "bird", "penguin", "elephant", "dromedary_camel", "camel", "boar", "pig2", "pig", "pig_nose", "dog2", "poodle", "dog", "wolf", "bear", "koala", "panda_face", "monkey_face", "see_no_evil", "hear_no_evil", "speak_no_evil", "monkey", "dragon", "dragon_face", "crocodile", "snake", "turtle", "frog", "whale2", "whale", "dolphin", "octopus", "fish", "tropical_fish", "blowfish", "shell", "snail", "bug", "ant", "bee", "beetle", "feet", "zap", "fire", "crescent_moon", "sunny", "partly_sunny", "cloud", "droplet", "sweat_drops", "umbrella", "dash", "snowflake", "star2", "star", "stars", "sunrise_over_mountains", "sunrise", "rainbow", "ocean", "volcano", "milky_way", "mount_fuji", "japan", "globe_with_meridians", "earth_africa", "earth_americas", "earth_asia", "new_moon", "waxing_crescent_moon", "first_quarter_moon", "moon", "full_moon", "waning_gibbous_moon", "last_quarter_moon", "waning_crescent_moon", "new_moon_with_face", "full_moon_with_face", "first_quarter_moon_with_face", "last_quarter_moon_with_face", "sun_with_face" ],
        Foods: [ "tomato", "eggplant", "corn", "sweet_potato", "grapes", "melon", "watermelon", "tangerine", "lemon", "banana", "pineapple", "apple", "green_apple", "pear", "peach", "cherries", "strawberry", "hamburger", "pizza", "meat_on_bone", "poultry_leg", "rice_cracker", "rice_ball", "rice", "curry", "ramen", "spaghetti", "bread", "fries", "dango", "oden", "sushi", "fried_shrimp", "fish_cake", "icecream", "shaved_ice", "ice_cream", "doughnut", "cookie", "chocolate_bar", "candy", "lollipop", "custard", "honey_pot", "cake", "bento", "stew", "egg", "fork_and_knife", "tea", "coffee", "sake", "wine_glass", "cocktail", "tropical_drink", "beer", "beers", "baby_bottle" ],
        People: [ "grinning", "grin", "joy", "smiley", "smile", "sweat_smile", "laughing", "innocent", "smiling_imp", "imp", "wink", "blush", "relaxed", "yum", "relieved", "heart_eyes", "sunglasses", "smirk", "neutral_face", "expressionless", "unamused", "sweat", "pensive", "confused", "confounded", "kissing", "kissing_heart", "kissing_smiling_eyes", "kissing_closed_eyes", "stuck_out_tongue", "stuck_out_tongue_winking_eye", "stuck_out_tongue_closed_eyes", "disappointed", "worried", "angry", "rage", "cry", "persevere", "triumph", "disappointed_relieved", "frowning", "anguished", "fearful", "weary", "sleepy", "tired_face", "grimacing", "sob", "open_mouth", "hushed", "cold_sweat", "scream", "astonished", "flushed", "sleeping", "dizzy_face", "no_mouth", "mask", "smile_cat", "joy_cat", "smiley_cat", "heart_eyes_cat", "smirk_cat", "kissing_cat", "pouting_cat", "crying_cat_face", "scream_cat", "footprints", "bust_in_silhouette", "busts_in_silhouette", "boy", "girl", "man", "woman", "family", "couple", "two_men_holding_hands", "two_women_holding_hands", "cop", "dancers", "bride_with_veil", "person_with_blond_hair", "man_with_gua_pi_mao", "man_with_turban", "older_man", "older_woman", "baby", "construction_worker", "princess", "guardsman", "angel", "santa", "ghost", "japanese_ogre", "japanese_goblin", "hankey", "skull", "alien", "space_invader", "bow", "information_desk_person", "no_good", "ok_woman", "raising_hand", "person_with_pouting_face", "person_frowning", "massage", "haircut", "couple_with_heart", "couplekiss", "nail_care", "ear", "eyes", "nose", "lips", "kiss", "tongue", "wave", "+1", "-1", "point_up", "point_up_2", "point_down", "point_left", "point_right", "ok_hand", "v", "facepunch", "fist", "hand", "muscle", "open_hands", "raised_hands", "clap", "pray" ],
        Places: [ "railway_car", "mountain_railway", "steam_locomotive", "train", "monorail", "bullettrain_side", "bullettrain_front", "train2", "metro", "light_rail", "station", "tram", "bus", "oncoming_bus", "trolleybus", "minibus", "ambulance", "fire_engine", "police_car", "oncoming_police_car", "rotating_light", "taxi", "oncoming_taxi", "car", "oncoming_automobile", "blue_car", "truck", "articulated_lorry", "tractor", "bike", "busstop", "fuelpump", "construction", "vertical_traffic_light", "traffic_light", "rocket", "helicopter", "airplane", "seat", "anchor", "ship", "speedboat", "boat", "aerial_tramway", "mountain_cableway", "suspension_railway", "passport_control", "customs", "baggage_claim", "left_luggage", "yen", "euro", "pound", "dollar", "statue_of_liberty", "moyai", "foggy", "tokyo_tower", "fountain", "european_castle", "japanese_castle", "city_sunrise", "city_sunset", "night_with_stars", "bridge_at_night", "house", "house_with_garden", "office", "department_store", "factory", "post_office", "european_post_office", "hospital", "bank", "hotel", "love_hotel", "wedding", "church", "convenience_store", "school", "flag-cn", "flag-fr", "flag-de", "flag-it", "flag-jp", "flag-kr", "flag-ru", "flag-es", "flag-gb", "flag-us" ],
        Activity: [ "runner", "walking", "dancer", "rowboat", "swimmer", "surfer", "bath", "snowboarder", "ski", "snowman", "bicyclist", "mountain_bicyclist", "horse_racing", "tent", "fishing_pole_and_fish", "soccer", "basketball", "football", "baseball", "tennis", "rugby_football", "golf", "trophy", "running_shirt_with_sash", "checkered_flag", "musical_keyboard", "guitar", "violin", "saxophone", "trumpet", "musical_note", "notes", "musical_score", "headphones", "microphone", "performing_arts", "ticket", "tophat", "circus_tent", "clapper", "art", "dart", "8ball", "bowling", "slot_machine", "game_die", "video_game", "flower_playing_cards", "black_joker", "mahjong", "carousel_horse", "ferris_wheel", "roller_coaster" ],
        Celebration: [ "ribbon", "gift", "birthday", "jack_o_lantern", "christmas_tree", "tanabata_tree", "bamboo", "rice_scene", "fireworks", "sparkler", "tada", "confetti_ball", "balloon", "dizzy", "sparkles", "boom", "mortar_board", "crown", "dolls", "flags", "wind_chime", "crossed_flags", "izakaya_lantern", "ring", "heart", "broken_heart", "love_letter", "two_hearts", "revolving_hearts", "heartbeat", "heartpulse", "sparkling_heart", "cupid", "gift_heart", "heart_decoration", "purple_heart", "yellow_heart", "green_heart", "blue_heart" ]
    },
    alternatives: {
        phone: [ "telephone" ],
        boat: [ "sailboat" ],
        email: [ "envelope" ],
        hand: [ "raised_hand" ],
        exclamation: [ "heavy_exclamation_mark" ],
        moon: [ "waxing_gibbous_moon" ],
        runner: [ "running" ],
        izakaya_lantern: [ "lantern" ],
        bee: [ "honeybee" ],
        dolphin: [ "flipper" ],
        feet: [ "paw_prints" ],
        facepunch: [ "punch" ],
        "+1": [ "thumbsup" ],
        "-1": [ "thumbsdown" ],
        shirt: [ "tshirt" ],
        mans_shoe: [ "shoe" ],
        boom: [ "collision" ],
        hankey: [ "poop", "shit" ],
        book: [ "open_book" ],
        memo: [ "pencil" ],
        hocho: [ "knife" ],
        laughing: [ "satisfied" ],
        car: [ "red_car" ],
        "flag-cn": [ "cn" ],
        "flag-de": [ "de" ],
        "flag-es": [ "es" ],
        "flag-fr": [ "fr" ],
        "flag-gb": [ "gb", "uk" ],
        "flag-it": [ "it" ],
        "flag-jp": [ "jp" ],
        "flag-kr": [ "kr" ],
        "flag-ru": [ "ru" ],
        "flag-us": [ "us" ],
        shipit: [ "squirrel" ]
    },
    codes: {
        "+1": [ [ "👍" ], 22, 7 ],
        "-1": [ [ "👎" ], 22, 13 ],
        100: [ [ "💯" ], 27, 3 ],
        1234: [ [ "🔢" ], 29, 2 ],
        "8ball": [ [ "🎱" ], 17, 10 ],
        a: [ [ "🅰", "🅰️" ], 3, 3 ],
        ab: [ [ "🆎" ], 4, 3 ],
        abc: [ [ "🔤" ], 29, 4 ],
        abcd: [ [ "🔡" ], 29, 1 ],
        accept: [ [ "🉑" ], 12, 3 ],
        aerial_tramway: [ [ "🚡" ], 32, 31 ],
        airplane: [ [ "✈", "✈️" ], 34, 34 ],
        alarm_clock: [ [ "⏰" ], 34, 5 ],
        alien: [ [ "👽" ], 25, 22 ],
        ambulance: [ [ "🚑" ], 32, 15 ],
        anchor: [ [ "⚓", "⚓️" ], 15, 34 ],
        angel: [ [ "👼" ], 25, 21 ],
        anger: [ [ "💢" ], 12, 26 ],
        angry: [ [ "😠" ], 8, 30 ],
        anguished: [ [ "😧" ], 15, 30 ],
        ant: [ [ "🐜" ], 14, 19 ],
        apple: [ [ "🍎" ], 0, 14 ],
        aquarius: [ [ "♒", "♒️" ], 6, 34 ],
        aries: [ [ "♈", "♈️" ], 34, 30 ],
        arrow_backward: [ [ "◀", "◀️" ], 34, 12 ],
        arrow_double_down: [ [ "⏬" ], 34, 4 ],
        arrow_double_up: [ [ "⏫" ], 34, 3 ],
        arrow_down: [ [ "⬇", "⬇️" ], 14, 35 ],
        arrow_down_small: [ [ "🔽" ], 0, 29 ],
        arrow_forward: [ [ "▶", "▶️" ], 34, 11 ],
        arrow_heading_down: [ [ "⤵", "⤵️" ], 10, 35 ],
        arrow_heading_up: [ [ "⤴", "⤴️" ], 9, 35 ],
        arrow_left: [ [ "⬅", "⬅️" ], 12, 35 ],
        arrow_lower_left: [ [ "↙", "↙️" ], 11, 33 ],
        arrow_lower_right: [ [ "↘", "↘️" ], 10, 33 ],
        arrow_right: [ [ "➡", "➡️" ], 3, 35 ],
        arrow_right_hook: [ [ "↪", "↪️" ], 14, 33 ],
        arrow_up: [ [ "⬆", "⬆️" ], 13, 35 ],
        arrow_up_down: [ [ "↕", "↕️" ], 7, 33 ],
        arrow_up_small: [ [ "🔼" ], 29, 28 ],
        arrow_upper_left: [ [ "↖", "↖️" ], 8, 33 ],
        arrow_upper_right: [ [ "↗", "↗️" ], 9, 33 ],
        arrows_clockwise: [ [ "🔃" ], 0, 28 ],
        arrows_counterclockwise: [ [ "🔄" ], 1, 28 ],
        art: [ [ "🎨" ], 17, 1 ],
        articulated_lorry: [ [ "🚛" ], 32, 25 ],
        astonished: [ [ "😲" ], 26, 30 ],
        athletic_shoe: [ [ "👟" ], 18, 22 ],
        atm: [ [ "🏧" ], 9, 18 ],
        b: [ [ "🅱", "🅱️" ], 4, 0 ],
        baby: [ [ "👶" ], 25, 0 ],
        baby_bottle: [ [ "🍼" ], 16, 0 ],
        baby_chick: [ [ "🐤" ], 20, 2 ],
        baby_symbol: [ [ "🚼" ], 33, 13 ],
        back: [ [ "🔙" ], 22, 28 ],
        baggage_claim: [ [ "🛄" ], 33, 26 ],
        balloon: [ [ "🎈" ], 16, 14 ],
        ballot_box_with_check: [ [ "☑", "☑️" ], 34, 20 ],
        bamboo: [ [ "🎍" ], 3, 16 ],
        banana: [ [ "🍌" ], 14, 12 ],
        bangbang: [ [ "‼", "‼️" ], 33, 28 ],
        bank: [ [ "🏦" ], 8, 18 ],
        bar_chart: [ [ "📊" ], 3, 27 ],
        barber: [ [ "💈" ], 26, 12 ],
        baseball: [ [ "⚾", "⚾️" ], 21, 34 ],
        basketball: [ [ "🏀" ], 8, 17 ],
        bath: [ [ "🛀" ], 33, 22 ],
        bathtub: [ [ "🛁" ], 33, 23 ],
        battery: [ [ "🔋" ], 8, 28 ],
        bear: [ [ "🐻" ], 5, 20 ],
        bee: [ [ "🐝" ], 15, 19 ],
        beer: [ [ "🍺" ], 14, 15 ],
        beers: [ [ "🍻" ], 15, 15 ],
        beetle: [ [ "🐞" ], 16, 19 ],
        beginner: [ [ "🔰" ], 29, 16 ],
        bell: [ [ "🔔" ], 17, 28 ],
        bento: [ [ "🍱" ], 5, 15 ],
        bicyclist: [ [ "🚴" ], 28, 32 ],
        bike: [ [ "🚲" ], 21, 32 ],
        bikini: [ [ "👙" ], 12, 22 ],
        bird: [ [ "🐦" ], 20, 4 ],
        birthday: [ [ "🎂" ], 16, 3 ],
        black_circle: [ [ "⚫", "⚫️" ], 19, 34 ],
        black_joker: [ [ "🃏" ], 2, 3 ],
        black_large_square: [ [ "⬛", "⬛️" ], 15, 35 ],
        black_medium_small_square: [ [ "◾", "◾️" ], 34, 16 ],
        black_medium_square: [ [ "◼", "◼️" ], 34, 14 ],
        black_nib: [ [ "✒", "✒️" ], 35, 20 ],
        black_small_square: [ [ "▪", "▪️" ], 34, 9 ],
        black_square_button: [ [ "🔲" ], 29, 18 ],
        blossom: [ [ "🌼" ], 10, 13 ],
        blowfish: [ [ "🐡" ], 19, 19 ],
        blue_book: [ [ "📘" ], 17, 27 ],
        blue_car: [ [ "🚙" ], 32, 23 ],
        blue_heart: [ [ "💙" ], 3, 26 ],
        blush: [ [ "😊" ], 30, 16 ],
        boar: [ [ "🐗" ], 9, 19 ],
        boat: [ [ "⛵", "⛵️" ], 29, 34 ],
        bomb: [ [ "💣" ], 13, 26 ],
        book: [ [ "📖" ], 15, 27 ],
        bookmark: [ [ "🔖" ], 19, 28 ],
        bookmark_tabs: [ [ "📑" ], 10, 27 ],
        books: [ [ "📚" ], 19, 27 ],
        boom: [ [ "💥" ], 15, 26 ],
        boot: [ [ "👢" ], 21, 22 ],
        bouquet: [ [ "💐" ], 26, 20 ],
        bow: [ [ "🙇" ], 31, 27 ],
        bowling: [ [ "🎳" ], 17, 12 ],
        boy: [ [ "👦" ], 23, 7 ],
        bread: [ [ "🍞" ], 15, 1 ],
        bride_with_veil: [ [ "👰" ], 24, 13 ],
        bridge_at_night: [ [ "🌉" ], 1, 12 ],
        briefcase: [ [ "💼" ], 27, 16 ],
        broken_heart: [ [ "💔" ], 26, 24 ],
        bug: [ [ "🐛" ], 13, 19 ],
        bulb: [ [ "💡" ], 11, 26 ],
        bullettrain_front: [ [ "🚅" ], 32, 3 ],
        bullettrain_side: [ [ "🚄" ], 32, 2 ],
        bus: [ [ "🚌" ], 32, 10 ],
        busstop: [ [ "🚏" ], 32, 13 ],
        bust_in_silhouette: [ [ "👤" ], 23, 0 ],
        busts_in_silhouette: [ [ "👥" ], 23, 1 ],
        cactus: [ [ "🌵" ], 4, 13 ],
        cake: [ [ "🍰" ], 4, 15 ],
        calendar: [ [ "📆" ], 27, 26 ],
        calling: [ [ "📲" ], 28, 15 ],
        camel: [ [ "🐫" ], 20, 9 ],
        camera: [ [ "📷" ], 28, 20 ],
        cancer: [ [ "♋", "♋️" ], 34, 33 ],
        candy: [ [ "🍬" ], 0, 15 ],
        capital_abcd: [ [ "🔠" ], 29, 0 ],
        capricorn: [ [ "♑", "♑️" ], 5, 34 ],
        car: [ [ "🚗" ], 32, 21 ],
        card_index: [ [ "📇" ], 0, 27 ],
        carousel_horse: [ [ "🎠" ], 10, 16 ],
        cat: [ [ "🐱" ], 20, 15 ],
        cat2: [ [ "🐈" ], 19, 13 ],
        cd: [ [ "💿" ], 27, 19 ],
        chart: [ [ "💹" ], 27, 13 ],
        chart_with_downwards_trend: [ [ "📉" ], 2, 27 ],
        chart_with_upwards_trend: [ [ "📈" ], 1, 27 ],
        checkered_flag: [ [ "🏁" ], 9, 17 ],
        cherries: [ [ "🍒" ], 4, 14 ],
        cherry_blossom: [ [ "🌸" ], 6, 13 ],
        chestnut: [ [ "🌰" ], 13, 12 ],
        chicken: [ [ "🐔" ], 6, 19 ],
        children_crossing: [ [ "🚸" ], 33, 9 ],
        chocolate_bar: [ [ "🍫" ], 15, 14 ],
        christmas_tree: [ [ "🎄" ], 16, 5 ],
        church: [ [ "⛪", "⛪️" ], 26, 34 ],
        cinema: [ [ "🎦" ], 16, 16 ],
        circus_tent: [ [ "🎪" ], 17, 3 ],
        city_sunrise: [ [ "🌇" ], 12, 11 ],
        city_sunset: [ [ "🌆" ], 12, 10 ],
        cl: [ [ "🆑" ], 0, 4 ],
        clap: [ [ "👏" ], 22, 19 ],
        clapper: [ [ "🎬" ], 17, 5 ],
        clipboard: [ [ "📋" ], 4, 27 ],
        clock1: [ [ "🕐" ], 1, 29 ],
        clock10: [ [ "🕙" ], 10, 29 ],
        clock1030: [ [ "🕥" ], 22, 29 ],
        clock11: [ [ "🕚" ], 11, 29 ],
        clock1130: [ [ "🕦" ], 23, 29 ],
        clock12: [ [ "🕛" ], 12, 29 ],
        clock1230: [ [ "🕧" ], 24, 29 ],
        clock130: [ [ "🕜" ], 13, 29 ],
        clock2: [ [ "🕑" ], 2, 29 ],
        clock230: [ [ "🕝" ], 14, 29 ],
        clock3: [ [ "🕒" ], 3, 29 ],
        clock330: [ [ "🕞" ], 15, 29 ],
        clock4: [ [ "🕓" ], 4, 29 ],
        clock430: [ [ "🕟" ], 16, 29 ],
        clock5: [ [ "🕔" ], 5, 29 ],
        clock530: [ [ "🕠" ], 17, 29 ],
        clock6: [ [ "🕕" ], 6, 29 ],
        clock630: [ [ "🕡" ], 18, 29 ],
        clock7: [ [ "🕖" ], 7, 29 ],
        clock730: [ [ "🕢" ], 19, 29 ],
        clock8: [ [ "🕗" ], 8, 29 ],
        clock830: [ [ "🕣" ], 20, 29 ],
        clock9: [ [ "🕘" ], 9, 29 ],
        clock930: [ [ "🕤" ], 21, 29 ],
        closed_book: [ [ "📕" ], 14, 27 ],
        closed_lock_with_key: [ [ "🔐" ], 13, 28 ],
        closed_umbrella: [ [ "🌂" ], 12, 6 ],
        cloud: [ [ "☁", "☁️" ], 34, 18 ],
        clubs: [ [ "♣", "♣️" ], 9, 34 ],
        cocktail: [ [ "🍸" ], 12, 15 ],
        coffee: [ [ "☕", "☕️" ], 34, 22 ],
        cold_sweat: [ [ "😰" ], 24, 30 ],
        computer: [ [ "💻" ], 27, 15 ],
        confetti_ball: [ [ "🎊" ], 0, 16 ],
        confounded: [ [ "😖" ], 30, 28 ],
        confused: [ [ "😕" ], 30, 27 ],
        congratulations: [ [ "㊗", "㊗️" ], 33, 35 ],
        construction: [ [ "🚧" ], 10, 32 ],
        construction_worker: [ [ "👷" ], 25, 6 ],
        convenience_store: [ [ "🏪" ], 12, 18 ],
        cookie: [ [ "🍪" ], 15, 13 ],
        cool: [ [ "🆒" ], 1, 4 ],
        cop: [ [ "👮" ], 24, 6 ],
        corn: [ [ "🌽" ], 11, 13 ],
        couple: [ [ "👫" ], 22, 23 ],
        couple_with_heart: [ [ "💑" ], 26, 21 ],
        couplekiss: [ [ "💏" ], 26, 19 ],
        cow: [ [ "🐮" ], 20, 12 ],
        cow2: [ [ "🐄" ], 19, 9 ],
        credit_card: [ [ "💳" ], 27, 7 ],
        crescent_moon: [ [ "🌙" ], 13, 4 ],
        crocodile: [ [ "🐊" ], 19, 15 ],
        crossed_flags: [ [ "🎌" ], 2, 16 ],
        crown: [ [ "👑" ], 4, 22 ],
        cry: [ [ "😢" ], 10, 30 ],
        crying_cat_face: [ [ "😿" ], 31, 8 ],
        crystal_ball: [ [ "🔮" ], 29, 14 ],
        cupid: [ [ "💘" ], 2, 26 ],
        curly_loop: [ [ "➰" ], 4, 35 ],
        currency_exchange: [ [ "💱" ], 27, 5 ],
        curry: [ [ "🍛" ], 13, 14 ],
        custard: [ [ "🍮" ], 2, 15 ],
        customs: [ [ "🛃" ], 33, 25 ],
        cyclone: [ [ "🌀" ], 12, 4 ],
        dancer: [ [ "💃" ], 18, 25 ],
        dancers: [ [ "👯" ], 24, 7 ],
        dango: [ [ "🍡" ], 15, 4 ],
        dart: [ [ "🎯" ], 17, 8 ],
        dash: [ [ "💨" ], 18, 26 ],
        date: [ [ "📅" ], 27, 25 ],
        deciduous_tree: [ [ "🌳" ], 2, 13 ],
        department_store: [ [ "🏬" ], 14, 18 ],
        diamond_shape_with_a_dot_inside: [ [ "💠" ], 10, 26 ],
        diamonds: [ [ "♦", "♦️" ], 11, 34 ],
        disappointed: [ [ "😞" ], 6, 30 ],
        disappointed_relieved: [ [ "😥" ], 13, 30 ],
        dizzy: [ [ "💫" ], 26, 26 ],
        dizzy_face: [ [ "😵" ], 29, 30 ],
        do_not_litter: [ [ "🚯" ], 18, 32 ],
        dog: [ [ "🐶" ], 0, 20 ],
        dog2: [ [ "🐕" ], 7, 19 ],
        dollar: [ [ "💵" ], 27, 9 ],
        dolls: [ [ "🎎" ], 4, 16 ],
        dolphin: [ [ "🐬" ], 20, 10 ],
        door: [ [ "🚪" ], 13, 32 ],
        doughnut: [ [ "🍩" ], 15, 12 ],
        dragon: [ [ "🐉" ], 19, 14 ],
        dragon_face: [ [ "🐲" ], 20, 16 ],
        dress: [ [ "👗" ], 10, 22 ],
        dromedary_camel: [ [ "🐪" ], 20, 8 ],
        droplet: [ [ "💧" ], 17, 26 ],
        dvd: [ [ "📀" ], 27, 20 ],
        "e-mail": [ [ "📧" ], 28, 4 ],
        ear: [ [ "👂" ], 15, 20 ],
        ear_of_rice: [ [ "🌾" ], 12, 13 ],
        earth_africa: [ [ "🌍" ], 5, 12 ],
        earth_americas: [ [ "🌎" ], 6, 12 ],
        earth_asia: [ [ "🌏" ], 7, 12 ],
        egg: [ [ "🍳" ], 7, 15 ],
        eggplant: [ [ "🍆" ], 14, 6 ],
        eight: [ [ "8⃣", "8️⃣" ], 3, 0 ],
        eight_pointed_black_star: [ [ "✴", "✴️" ], 35, 25 ],
        eight_spoked_asterisk: [ [ "✳", "✳️" ], 35, 24 ],
        electric_plug: [ [ "🔌" ], 9, 28 ],
        elephant: [ [ "🐘" ], 10, 19 ],
        email: [ [ "✉", "✉️" ], 35, 0 ],
        end: [ [ "🔚" ], 23, 28 ],
        envelope_with_arrow: [ [ "📩" ], 28, 6 ],
        euro: [ [ "💶" ], 27, 10 ],
        european_castle: [ [ "🏰" ], 18, 18 ],
        european_post_office: [ [ "🏤" ], 6, 18 ],
        evergreen_tree: [ [ "🌲" ], 1, 13 ],
        exclamation: [ [ "❗", "❗️" ], 35, 33 ],
        expressionless: [ [ "😑" ], 30, 23 ],
        eyeglasses: [ [ "👓" ], 6, 22 ],
        eyes: [ [ "👀" ], 9, 20 ],
        facepunch: [ [ "👊" ], 11, 21 ],
        factory: [ [ "🏭" ], 15, 18 ],
        fallen_leaf: [ [ "🍂" ], 14, 2 ],
        family: [ [ "👪" ], 21, 23 ],
        fast_forward: [ [ "⏩" ], 34, 1 ],
        fax: [ [ "📠" ], 25, 27 ],
        fearful: [ [ "😨" ], 16, 30 ],
        feet: [ [ "🐾" ], 8, 20 ],
        ferris_wheel: [ [ "🎡" ], 11, 16 ],
        file_folder: [ [ "📁" ], 27, 21 ],
        fire: [ [ "🔥" ], 29, 5 ],
        fire_engine: [ [ "🚒" ], 32, 16 ],
        fireworks: [ [ "🎆" ], 16, 12 ],
        first_quarter_moon: [ [ "🌓" ], 11, 12 ],
        first_quarter_moon_with_face: [ [ "🌛" ], 13, 6 ],
        fish: [ [ "🐟" ], 17, 19 ],
        fish_cake: [ [ "🍥" ], 15, 8 ],
        fishing_pole_and_fish: [ [ "🎣" ], 13, 16 ],
        fist: [ [ "✊" ], 35, 6 ],
        five: [ [ "5⃣", "5️⃣" ], 0, 2 ],
        "flag-cn": [ [ "🇨🇳" ], 2, 6 ],
        "flag-de": [ [ "🇩🇪" ], 7, 3 ],
        "flag-es": [ [ "🇪🇸" ], 6, 7 ],
        "flag-fr": [ [ "🇫🇷" ], 8, 3 ],
        "flag-gb": [ [ "🇬🇧" ], 8, 5 ],
        "flag-it": [ [ "🇮🇹" ], 2, 9 ],
        "flag-jp": [ [ "🇯🇵" ], 5, 9 ],
        "flag-kr": [ [ "🇰🇷" ], 10, 3 ],
        "flag-ru": [ [ "🇷🇺" ], 10, 10 ],
        "flag-us": [ [ "🇺🇸" ], 11, 7 ],
        flags: [ [ "🎏" ], 5, 16 ],
        flashlight: [ [ "🔦" ], 29, 6 ],
        floppy_disk: [ [ "💾" ], 27, 18 ],
        flower_playing_cards: [ [ "🎴" ], 17, 13 ],
        flushed: [ [ "😳" ], 27, 30 ],
        foggy: [ [ "🌁" ], 12, 5 ],
        football: [ [ "🏈" ], 18, 12 ],
        footprints: [ [ "👣" ], 22, 22 ],
        fork_and_knife: [ [ "🍴" ], 8, 15 ],
        fountain: [ [ "⛲", "⛲️" ], 27, 34 ],
        four: [ [ "4⃣", "4️⃣" ], 2, 1 ],
        four_leaf_clover: [ [ "🍀" ], 14, 0 ],
        free: [ [ "🆓" ], 2, 4 ],
        fried_shrimp: [ [ "🍤" ], 15, 7 ],
        fries: [ [ "🍟" ], 15, 2 ],
        frog: [ [ "🐸" ], 2, 20 ],
        frowning: [ [ "😦" ], 14, 30 ],
        fuelpump: [ [ "⛽", "⛽️" ], 31, 34 ],
        full_moon: [ [ "🌕" ], 13, 0 ],
        full_moon_with_face: [ [ "🌝" ], 13, 8 ],
        game_die: [ [ "🎲" ], 17, 11 ],
        gem: [ [ "💎" ], 26, 18 ],
        gemini: [ [ "♊", "♊️" ], 34, 32 ],
        ghost: [ [ "👻" ], 25, 15 ],
        gift: [ [ "🎁" ], 16, 2 ],
        gift_heart: [ [ "💝" ], 7, 26 ],
        girl: [ [ "👧" ], 23, 13 ],
        globe_with_meridians: [ [ "🌐" ], 8, 12 ],
        goat: [ [ "🐐" ], 2, 19 ],
        golf: [ [ "⛳", "⛳️" ], 28, 34 ],
        grapes: [ [ "🍇" ], 14, 7 ],
        green_apple: [ [ "🍏" ], 1, 14 ],
        green_book: [ [ "📗" ], 16, 27 ],
        green_heart: [ [ "💚" ], 4, 26 ],
        grey_exclamation: [ [ "❕" ], 35, 32 ],
        grey_question: [ [ "❔" ], 35, 31 ],
        grimacing: [ [ "😬" ], 20, 30 ],
        grin: [ [ "😁" ], 30, 7 ],
        grinning: [ [ "😀" ], 30, 6 ],
        guardsman: [ [ "💂" ], 12, 25 ],
        guitar: [ [ "🎸" ], 0, 17 ],
        gun: [ [ "🔫" ], 29, 11 ],
        haircut: [ [ "💇" ], 26, 11 ],
        hamburger: [ [ "🍔" ], 6, 14 ],
        hammer: [ [ "🔨" ], 29, 8 ],
        hamster: [ [ "🐹" ], 3, 20 ],
        hand: [ [ "✋" ], 35, 12 ],
        handbag: [ [ "👜" ], 15, 22 ],
        hankey: [ [ "💩" ], 19, 26 ],
        hash: [ [ "#⃣", "#️⃣" ], 1, 0 ],
        hatched_chick: [ [ "🐥" ], 20, 3 ],
        hatching_chick: [ [ "🐣" ], 20, 1 ],
        headphones: [ [ "🎧" ], 17, 0 ],
        hear_no_evil: [ [ "🙉" ], 31, 29 ],
        heart: [ [ "❤", "❤️" ], 35, 34 ],
        heart_decoration: [ [ "💟" ], 9, 26 ],
        heart_eyes: [ [ "😍" ], 30, 19 ],
        heart_eyes_cat: [ [ "😻" ], 31, 4 ],
        heartbeat: [ [ "💓" ], 26, 23 ],
        heartpulse: [ [ "💗" ], 1, 26 ],
        hearts: [ [ "♥", "♥️" ], 10, 34 ],
        heavy_check_mark: [ [ "✔", "✔️" ], 35, 21 ],
        heavy_division_sign: [ [ "➗" ], 2, 35 ],
        heavy_dollar_sign: [ [ "💲" ], 27, 6 ],
        heavy_minus_sign: [ [ "➖" ], 1, 35 ],
        heavy_multiplication_x: [ [ "✖", "✖️" ], 35, 22 ],
        heavy_plus_sign: [ [ "➕" ], 0, 35 ],
        helicopter: [ [ "🚁" ], 31, 31 ],
        herb: [ [ "🌿" ], 13, 13 ],
        hibiscus: [ [ "🌺" ], 8, 13 ],
        high_brightness: [ [ "🔆" ], 3, 28 ],
        high_heel: [ [ "👠" ], 19, 22 ],
        hocho: [ [ "🔪" ], 29, 10 ],
        honey_pot: [ [ "🍯" ], 3, 15 ],
        horse: [ [ "🐴" ], 20, 18 ],
        horse_racing: [ [ "🏇" ], 18, 11 ],
        hospital: [ [ "🏥" ], 7, 18 ],
        hotel: [ [ "🏨" ], 10, 18 ],
        hotsprings: [ [ "♨", "♨️" ], 12, 34 ],
        hourglass: [ [ "⌛", "⌛️" ], 27, 33 ],
        hourglass_flowing_sand: [ [ "⏳" ], 34, 6 ],
        house: [ [ "🏠" ], 2, 18 ],
        house_with_garden: [ [ "🏡" ], 3, 18 ],
        hushed: [ [ "😯" ], 23, 30 ],
        ice_cream: [ [ "🍨" ], 15, 11 ],
        icecream: [ [ "🍦" ], 15, 9 ],
        id: [ [ "🆔" ], 3, 4 ],
        ideograph_advantage: [ [ "🉐" ], 12, 2 ],
        imp: [ [ "👿" ], 25, 24 ],
        inbox_tray: [ [ "📥" ], 28, 2 ],
        incoming_envelope: [ [ "📨" ], 28, 5 ],
        information_desk_person: [ [ "💁" ], 6, 25 ],
        information_source: [ [ "ℹ", "ℹ️" ], 1, 33 ],
        innocent: [ [ "😇" ], 30, 13 ],
        interrobang: [ [ "⁉", "⁉️" ], 33, 29 ],
        iphone: [ [ "📱" ], 28, 14 ],
        izakaya_lantern: [ [ "🏮" ], 16, 18 ],
        jack_o_lantern: [ [ "🎃" ], 16, 4 ],
        japan: [ [ "🗾" ], 30, 4 ],
        japanese_castle: [ [ "🏯" ], 17, 18 ],
        japanese_goblin: [ [ "👺" ], 25, 14 ],
        japanese_ogre: [ [ "👹" ], 25, 13 ],
        jeans: [ [ "👖" ], 9, 22 ],
        joy: [ [ "😂" ], 30, 8 ],
        joy_cat: [ [ "😹" ], 31, 2 ],
        key: [ [ "🔑" ], 14, 28 ],
        keycap_ten: [ [ "🔟" ], 28, 28 ],
        kimono: [ [ "👘" ], 11, 22 ],
        kiss: [ [ "💋" ], 26, 15 ],
        kissing: [ [ "😗" ], 30, 29 ],
        kissing_cat: [ [ "😽" ], 31, 6 ],
        kissing_closed_eyes: [ [ "😚" ], 2, 30 ],
        kissing_heart: [ [ "😘" ], 0, 30 ],
        kissing_smiling_eyes: [ [ "😙" ], 1, 30 ],
        koala: [ [ "🐨" ], 20, 6 ],
        koko: [ [ "🈁" ], 1, 11 ],
        large_blue_circle: [ [ "🔵" ], 29, 21 ],
        large_blue_diamond: [ [ "🔷" ], 29, 23 ],
        large_orange_diamond: [ [ "🔶" ], 29, 22 ],
        last_quarter_moon: [ [ "🌗" ], 13, 2 ],
        last_quarter_moon_with_face: [ [ "🌜" ], 13, 7 ],
        laughing: [ [ "😆" ], 30, 12 ],
        leaves: [ [ "🍃" ], 14, 3 ],
        ledger: [ [ "📒" ], 11, 27 ],
        left_luggage: [ [ "🛅" ], 33, 27 ],
        left_right_arrow: [ [ "↔", "↔️" ], 6, 33 ],
        leftwards_arrow_with_hook: [ [ "↩", "↩️" ], 13, 33 ],
        lemon: [ [ "🍋" ], 14, 11 ],
        leo: [ [ "♌", "♌️" ], 0, 34 ],
        leopard: [ [ "🐆" ], 19, 11 ],
        libra: [ [ "♎", "♎️" ], 2, 34 ],
        light_rail: [ [ "🚈" ], 32, 6 ],
        link: [ [ "🔗" ], 20, 28 ],
        lips: [ [ "👄" ], 21, 1 ],
        lipstick: [ [ "💄" ], 19, 25 ],
        lock: [ [ "🔒" ], 15, 28 ],
        lock_with_ink_pen: [ [ "🔏" ], 12, 28 ],
        lollipop: [ [ "🍭" ], 1, 15 ],
        loop: [ [ "➿" ], 5, 35 ],
        loud_sound: [ [ "🔊" ], 7, 28 ],
        loudspeaker: [ [ "📢" ], 27, 27 ],
        love_hotel: [ [ "🏩" ], 11, 18 ],
        love_letter: [ [ "💌" ], 26, 16 ],
        low_brightness: [ [ "🔅" ], 2, 28 ],
        m: [ [ "Ⓜ", "Ⓜ️" ], 34, 8 ],
        mag: [ [ "🔍" ], 10, 28 ],
        mag_right: [ [ "🔎" ], 11, 28 ],
        mahjong: [ [ "🀄", "🀄️" ], 1, 3 ],
        mailbox: [ [ "📫" ], 28, 8 ],
        mailbox_closed: [ [ "📪" ], 28, 7 ],
        mailbox_with_mail: [ [ "📬" ], 28, 9 ],
        mailbox_with_no_mail: [ [ "📭" ], 28, 10 ],
        man: [ [ "👨" ], 7, 23 ],
        man_with_gua_pi_mao: [ [ "👲" ], 1, 24 ],
        man_with_turban: [ [ "👳" ], 7, 24 ],
        mans_shoe: [ [ "👞" ], 17, 22 ],
        maple_leaf: [ [ "🍁" ], 14, 1 ],
        mask: [ [ "😷" ], 31, 0 ],
        massage: [ [ "💆" ], 26, 5 ],
        meat_on_bone: [ [ "🍖" ], 8, 14 ],
        mega: [ [ "📣" ], 28, 0 ],
        melon: [ [ "🍈" ], 14, 8 ],
        memo: [ [ "📝" ], 22, 27 ],
        mens: [ [ "🚹" ], 33, 10 ],
        metro: [ [ "🚇" ], 32, 5 ],
        microphone: [ [ "🎤" ], 14, 16 ],
        microscope: [ [ "🔬" ], 29, 12 ],
        milky_way: [ [ "🌌" ], 4, 12 ],
        minibus: [ [ "🚐" ], 32, 14 ],
        minidisc: [ [ "💽" ], 27, 17 ],
        mobile_phone_off: [ [ "📴" ], 28, 17 ],
        money_with_wings: [ [ "💸" ], 27, 12 ],
        moneybag: [ [ "💰" ], 27, 4 ],
        monkey: [ [ "🐒" ], 4, 19 ],
        monkey_face: [ [ "🐵" ], 20, 19 ],
        monorail: [ [ "🚝" ], 32, 27 ],
        moon: [ [ "🌔" ], 12, 12 ],
        mortar_board: [ [ "🎓" ], 9, 16 ],
        mount_fuji: [ [ "🗻" ], 30, 1 ],
        mountain_bicyclist: [ [ "🚵" ], 33, 1 ],
        mountain_cableway: [ [ "🚠" ], 32, 30 ],
        mountain_railway: [ [ "🚞" ], 32, 28 ],
        mouse: [ [ "🐭" ], 20, 11 ],
        mouse2: [ [ "🐁" ], 19, 6 ],
        movie_camera: [ [ "🎥" ], 15, 16 ],
        moyai: [ [ "🗿" ], 30, 5 ],
        muscle: [ [ "💪" ], 25, 26 ],
        mushroom: [ [ "🍄" ], 14, 4 ],
        musical_keyboard: [ [ "🎹" ], 1, 17 ],
        musical_note: [ [ "🎵" ], 17, 14 ],
        musical_score: [ [ "🎼" ], 4, 17 ],
        mute: [ [ "🔇" ], 4, 28 ],
        nail_care: [ [ "💅" ], 25, 25 ],
        name_badge: [ [ "📛" ], 20, 27 ],
        necktie: [ [ "👔" ], 7, 22 ],
        negative_squared_cross_mark: [ [ "❎" ], 35, 29 ],
        neutral_face: [ [ "😐" ], 30, 22 ],
        new: [ [ "🆕" ], 4, 4 ],
        new_moon: [ [ "🌑" ], 9, 12 ],
        new_moon_with_face: [ [ "🌚" ], 13, 5 ],
        newspaper: [ [ "📰" ], 28, 13 ],
        ng: [ [ "🆖" ], 5, 0 ],
        night_with_stars: [ [ "🌃" ], 12, 7 ],
        nine: [ [ "9⃣", "9️⃣" ], 3, 1 ],
        no_bell: [ [ "🔕" ], 18, 28 ],
        no_bicycles: [ [ "🚳" ], 22, 32 ],
        no_entry: [ [ "⛔", "⛔️" ], 25, 34 ],
        no_entry_sign: [ [ "🚫" ], 14, 32 ],
        no_good: [ [ "🙅" ], 31, 15 ],
        no_mobile_phones: [ [ "📵" ], 28, 18 ],
        no_mouth: [ [ "😶" ], 30, 30 ],
        no_pedestrians: [ [ "🚷" ], 33, 8 ],
        no_smoking: [ [ "🚭" ], 16, 32 ],
        "non-potable_water": [ [ "🚱" ], 20, 32 ],
        nose: [ [ "👃" ], 21, 0 ],
        notebook: [ [ "📓" ], 12, 27 ],
        notebook_with_decorative_cover: [ [ "📔" ], 13, 27 ],
        notes: [ [ "🎶" ], 17, 15 ],
        nut_and_bolt: [ [ "🔩" ], 29, 9 ],
        o: [ [ "⭕", "⭕️" ], 18, 35 ],
        o2: [ [ "🅾", "🅾️" ], 4, 1 ],
        ocean: [ [ "🌊" ], 2, 12 ],
        octopus: [ [ "🐙" ], 11, 19 ],
        oden: [ [ "🍢" ], 15, 5 ],
        office: [ [ "🏢" ], 4, 18 ],
        ok: [ [ "🆗" ], 5, 1 ],
        ok_hand: [ [ "👌" ], 22, 1 ],
        ok_woman: [ [ "🙆" ], 31, 21 ],
        older_man: [ [ "👴" ], 13, 24 ],
        older_woman: [ [ "👵" ], 19, 24 ],
        on: [ [ "🔛" ], 24, 28 ],
        oncoming_automobile: [ [ "🚘" ], 32, 22 ],
        oncoming_bus: [ [ "🚍" ], 32, 11 ],
        oncoming_police_car: [ [ "🚔" ], 32, 18 ],
        oncoming_taxi: [ [ "🚖" ], 32, 20 ],
        one: [ [ "1⃣", "1️⃣" ], 0, 1 ],
        open_file_folder: [ [ "📂" ], 27, 22 ],
        open_hands: [ [ "👐" ], 3, 22 ],
        open_mouth: [ [ "😮" ], 22, 30 ],
        ophiuchus: [ [ "⛎" ], 24, 34 ],
        orange_book: [ [ "📙" ], 18, 27 ],
        outbox_tray: [ [ "📤" ], 28, 1 ],
        ox: [ [ "🐂" ], 19, 7 ],
        package: [ [ "📦" ], 28, 3 ],
        page_facing_up: [ [ "📄" ], 27, 24 ],
        page_with_curl: [ [ "📃" ], 27, 23 ],
        pager: [ [ "📟" ], 24, 27 ],
        palm_tree: [ [ "🌴" ], 3, 13 ],
        panda_face: [ [ "🐼" ], 6, 20 ],
        paperclip: [ [ "📎" ], 7, 27 ],
        parking: [ [ "🅿", "🅿️" ], 4, 2 ],
        part_alternation_mark: [ [ "〽", "〽️" ], 20, 35 ],
        partly_sunny: [ [ "⛅", "⛅️" ], 23, 34 ],
        passport_control: [ [ "🛂" ], 33, 24 ],
        peach: [ [ "🍑" ], 3, 14 ],
        pear: [ [ "🍐" ], 2, 14 ],
        pencil2: [ [ "✏", "✏️" ], 35, 19 ],
        penguin: [ [ "🐧" ], 20, 5 ],
        pensive: [ [ "😔" ], 30, 26 ],
        performing_arts: [ [ "🎭" ], 17, 6 ],
        persevere: [ [ "😣" ], 11, 30 ],
        person_frowning: [ [ "🙍" ], 17, 31 ],
        person_with_blond_hair: [ [ "👱" ], 24, 19 ],
        person_with_pouting_face: [ [ "🙎" ], 23, 31 ],
        phone: [ [ "☎", "☎️" ], 34, 19 ],
        pig: [ [ "🐷" ], 1, 20 ],
        pig2: [ [ "🐖" ], 8, 19 ],
        pig_nose: [ [ "🐽" ], 7, 20 ],
        pill: [ [ "💊" ], 26, 14 ],
        pineapple: [ [ "🍍" ], 14, 13 ],
        pisces: [ [ "♓", "♓️" ], 7, 34 ],
        pizza: [ [ "🍕" ], 7, 14 ],
        point_down: [ [ "👇" ], 21, 14 ],
        point_left: [ [ "👈" ], 21, 20 ],
        point_right: [ [ "👉" ], 5, 21 ],
        point_up: [ [ "☝", "☝️" ], 34, 28 ],
        point_up_2: [ [ "👆" ], 21, 8 ],
        police_car: [ [ "🚓" ], 32, 17 ],
        poodle: [ [ "🐩" ], 20, 7 ],
        post_office: [ [ "🏣" ], 5, 18 ],
        postal_horn: [ [ "📯" ], 28, 12 ],
        postbox: [ [ "📮" ], 28, 11 ],
        potable_water: [ [ "🚰" ], 19, 32 ],
        pouch: [ [ "👝" ], 16, 22 ],
        poultry_leg: [ [ "🍗" ], 9, 14 ],
        pound: [ [ "💷" ], 27, 11 ],
        pouting_cat: [ [ "😾" ], 31, 7 ],
        pray: [ [ "🙏" ], 29, 31 ],
        princess: [ [ "👸" ], 25, 12 ],
        purple_heart: [ [ "💜" ], 6, 26 ],
        purse: [ [ "👛" ], 14, 22 ],
        pushpin: [ [ "📌" ], 5, 27 ],
        put_litter_in_its_place: [ [ "🚮" ], 17, 32 ],
        question: [ [ "❓" ], 35, 30 ],
        rabbit: [ [ "🐰" ], 20, 14 ],
        rabbit2: [ [ "🐇" ], 19, 12 ],
        racehorse: [ [ "🐎" ], 0, 19 ],
        radio: [ [ "📻" ], 28, 23 ],
        radio_button: [ [ "🔘" ], 21, 28 ],
        rage: [ [ "😡" ], 9, 30 ],
        railway_car: [ [ "🚃" ], 32, 1 ],
        rainbow: [ [ "🌈" ], 0, 12 ],
        raised_hands: [ [ "🙌" ], 11, 31 ],
        raising_hand: [ [ "🙋" ], 5, 31 ],
        ram: [ [ "🐏" ], 1, 19 ],
        ramen: [ [ "🍜" ], 14, 14 ],
        rat: [ [ "🐀" ], 19, 5 ],
        recycle: [ [ "♻", "♻️" ], 13, 34 ],
        red_circle: [ [ "🔴" ], 29, 20 ],
        relaxed: [ [ "☺", "☺️" ], 34, 29 ],
        relieved: [ [ "😌" ], 30, 18 ],
        repeat: [ [ "🔁" ], 28, 26 ],
        repeat_one: [ [ "🔂" ], 28, 27 ],
        restroom: [ [ "🚻" ], 33, 12 ],
        revolving_hearts: [ [ "💞" ], 8, 26 ],
        rewind: [ [ "⏪" ], 34, 2 ],
        ribbon: [ [ "🎀" ], 16, 1 ],
        rice: [ [ "🍚" ], 12, 14 ],
        rice_ball: [ [ "🍙" ], 11, 14 ],
        rice_cracker: [ [ "🍘" ], 10, 14 ],
        rice_scene: [ [ "🎑" ], 7, 16 ],
        ring: [ [ "💍" ], 26, 17 ],
        rocket: [ [ "🚀" ], 30, 31 ],
        roller_coaster: [ [ "🎢" ], 12, 16 ],
        rooster: [ [ "🐓" ], 5, 19 ],
        rose: [ [ "🌹" ], 7, 13 ],
        rotating_light: [ [ "🚨" ], 11, 32 ],
        round_pushpin: [ [ "📍" ], 6, 27 ],
        rowboat: [ [ "🚣" ], 6, 32 ],
        rugby_football: [ [ "🏉" ], 18, 13 ],
        runner: [ [ "🏃" ], 16, 17 ],
        running_shirt_with_sash: [ [ "🎽" ], 5, 17 ],
        sa: [ [ "🈂", "🈂️" ], 2, 11 ],
        sagittarius: [ [ "♐", "♐️" ], 4, 34 ],
        sake: [ [ "🍶" ], 10, 15 ],
        sandal: [ [ "👡" ], 20, 22 ],
        santa: [ [ "🎅" ], 16, 11 ],
        satellite: [ [ "📡" ], 26, 27 ],
        saxophone: [ [ "🎷" ], 17, 16 ],
        school: [ [ "🏫" ], 13, 18 ],
        school_satchel: [ [ "🎒" ], 8, 16 ],
        scissors: [ [ "✂", "✂️" ], 32, 34 ],
        scorpius: [ [ "♏", "♏️" ], 3, 34 ],
        scream: [ [ "😱" ], 25, 30 ],
        scream_cat: [ [ "🙀" ], 31, 9 ],
        scroll: [ [ "📜" ], 21, 27 ],
        seat: [ [ "💺" ], 27, 14 ],
        secret: [ [ "㊙", "㊙️" ], 34, 35 ],
        see_no_evil: [ [ "🙈" ], 31, 28 ],
        seedling: [ [ "🌱" ], 0, 13 ],
        seven: [ [ "7⃣", "7️⃣" ], 2, 2 ],
        shaved_ice: [ [ "🍧" ], 15, 10 ],
        sheep: [ [ "🐑" ], 3, 19 ],
        shell: [ [ "🐚" ], 12, 19 ],
        ship: [ [ "🚢" ], 0, 32 ],
        shirt: [ [ "👕" ], 8, 22 ],
        shower: [ [ "🚿" ], 33, 16 ],
        signal_strength: [ [ "📶" ], 28, 19 ],
        six: [ [ "6⃣", "6️⃣" ], 1, 2 ],
        six_pointed_star: [ [ "🔯" ], 29, 15 ],
        ski: [ [ "🎿" ], 7, 17 ],
        skull: [ [ "💀" ], 0, 25 ],
        sleeping: [ [ "😴" ], 28, 30 ],
        sleepy: [ [ "😪" ], 18, 30 ],
        slot_machine: [ [ "🎰" ], 17, 9 ],
        small_blue_diamond: [ [ "🔹" ], 29, 25 ],
        small_orange_diamond: [ [ "🔸" ], 29, 24 ],
        small_red_triangle: [ [ "🔺" ], 29, 26 ],
        small_red_triangle_down: [ [ "🔻" ], 29, 27 ],
        smile: [ [ "😄" ], 30, 10 ],
        smile_cat: [ [ "😸" ], 31, 1 ],
        smiley: [ [ "😃" ], 30, 9 ],
        smiley_cat: [ [ "😺" ], 31, 3 ],
        smiling_imp: [ [ "😈" ], 30, 14 ],
        smirk: [ [ "😏" ], 30, 21 ],
        smirk_cat: [ [ "😼" ], 31, 5 ],
        smoking: [ [ "🚬" ], 15, 32 ],
        snail: [ [ "🐌" ], 19, 17 ],
        snake: [ [ "🐍" ], 19, 18 ],
        snowboarder: [ [ "🏂" ], 10, 17 ],
        snowflake: [ [ "❄", "❄️" ], 35, 26 ],
        snowman: [ [ "⛄", "⛄️" ], 22, 34 ],
        sob: [ [ "😭" ], 21, 30 ],
        soccer: [ [ "⚽", "⚽️" ], 20, 34 ],
        soon: [ [ "🔜" ], 25, 28 ],
        sos: [ [ "🆘" ], 5, 2 ],
        sound: [ [ "🔉" ], 6, 28 ],
        space_invader: [ [ "👾" ], 25, 23 ],
        spades: [ [ "♠", "♠️" ], 8, 34 ],
        spaghetti: [ [ "🍝" ], 15, 0 ],
        sparkle: [ [ "❇", "❇️" ], 35, 27 ],
        sparkler: [ [ "🎇" ], 16, 13 ],
        sparkles: [ [ "✨" ], 35, 23 ],
        sparkling_heart: [ [ "💖" ], 0, 26 ],
        speak_no_evil: [ [ "🙊" ], 31, 30 ],
        speaker: [ [ "🔈" ], 5, 28 ],
        speech_balloon: [ [ "💬" ], 27, 0 ],
        speedboat: [ [ "🚤" ], 7, 32 ],
        star: [ [ "⭐", "⭐️" ], 17, 35 ],
        star2: [ [ "🌟" ], 13, 10 ],
        stars: [ [ "🌠" ], 13, 11 ],
        station: [ [ "🚉" ], 32, 7 ],
        statue_of_liberty: [ [ "🗽" ], 30, 3 ],
        steam_locomotive: [ [ "🚂" ], 32, 0 ],
        stew: [ [ "🍲" ], 6, 15 ],
        straight_ruler: [ [ "📏" ], 8, 27 ],
        strawberry: [ [ "🍓" ], 5, 14 ],
        stuck_out_tongue: [ [ "😛" ], 3, 30 ],
        stuck_out_tongue_closed_eyes: [ [ "😝" ], 5, 30 ],
        stuck_out_tongue_winking_eye: [ [ "😜" ], 4, 30 ],
        sun_with_face: [ [ "🌞" ], 13, 9 ],
        sunflower: [ [ "🌻" ], 9, 13 ],
        sunglasses: [ [ "😎" ], 30, 20 ],
        sunny: [ [ "☀", "☀️" ], 34, 17 ],
        sunrise: [ [ "🌅" ], 12, 9 ],
        sunrise_over_mountains: [ [ "🌄" ], 12, 8 ],
        surfer: [ [ "🏄" ], 18, 4 ],
        sushi: [ [ "🍣" ], 15, 6 ],
        suspension_railway: [ [ "🚟" ], 32, 29 ],
        sweat: [ [ "😓" ], 30, 25 ],
        sweat_drops: [ [ "💦" ], 16, 26 ],
        sweat_smile: [ [ "😅" ], 30, 11 ],
        sweet_potato: [ [ "🍠" ], 15, 3 ],
        swimmer: [ [ "🏊" ], 1, 18 ],
        symbols: [ [ "🔣" ], 29, 3 ],
        syringe: [ [ "💉" ], 26, 13 ],
        tada: [ [ "🎉" ], 16, 15 ],
        tanabata_tree: [ [ "🎋" ], 1, 16 ],
        tangerine: [ [ "🍊" ], 14, 10 ],
        taurus: [ [ "♉", "♉️" ], 34, 31 ],
        taxi: [ [ "🚕" ], 32, 19 ],
        tea: [ [ "🍵" ], 9, 15 ],
        telephone_receiver: [ [ "📞" ], 23, 27 ],
        telescope: [ [ "🔭" ], 29, 13 ],
        tennis: [ [ "🎾" ], 6, 17 ],
        tent: [ [ "⛺", "⛺️" ], 30, 34 ],
        thought_balloon: [ [ "💭" ], 27, 1 ],
        three: [ [ "3⃣", "3️⃣" ], 2, 0 ],
        ticket: [ [ "🎫" ], 17, 4 ],
        tiger: [ [ "🐯" ], 20, 13 ],
        tiger2: [ [ "🐅" ], 19, 10 ],
        tired_face: [ [ "😫" ], 19, 30 ],
        tm: [ [ "™", "™️" ], 33, 32 ],
        toilet: [ [ "🚽" ], 33, 14 ],
        tokyo_tower: [ [ "🗼" ], 30, 2 ],
        tomato: [ [ "🍅" ], 14, 5 ],
        tongue: [ [ "👅" ], 21, 2 ],
        top: [ [ "🔝" ], 26, 28 ],
        tophat: [ [ "🎩" ], 17, 2 ],
        tractor: [ [ "🚜" ], 32, 26 ],
        traffic_light: [ [ "🚥" ], 8, 32 ],
        train: [ [ "🚋" ], 32, 9 ],
        train2: [ [ "🚆" ], 32, 4 ],
        tram: [ [ "🚊" ], 32, 8 ],
        triangular_flag_on_post: [ [ "🚩" ], 12, 32 ],
        triangular_ruler: [ [ "📐" ], 9, 27 ],
        trident: [ [ "🔱" ], 29, 17 ],
        triumph: [ [ "😤" ], 12, 30 ],
        trolleybus: [ [ "🚎" ], 32, 12 ],
        trophy: [ [ "🏆" ], 18, 5 ],
        tropical_drink: [ [ "🍹" ], 13, 15 ],
        tropical_fish: [ [ "🐠" ], 18, 19 ],
        truck: [ [ "🚚" ], 32, 24 ],
        trumpet: [ [ "🎺" ], 2, 17 ],
        tulip: [ [ "🌷" ], 5, 13 ],
        turtle: [ [ "🐢" ], 20, 0 ],
        tv: [ [ "📺" ], 28, 22 ],
        twisted_rightwards_arrows: [ [ "🔀" ], 28, 25 ],
        two: [ [ "2⃣", "2️⃣" ], 1, 1 ],
        two_hearts: [ [ "💕" ], 26, 25 ],
        two_men_holding_hands: [ [ "👬" ], 23, 23 ],
        two_women_holding_hands: [ [ "👭" ], 24, 0 ],
        u5272: [ [ "🈹" ], 12, 0 ],
        u5408: [ [ "🈴" ], 7, 11 ],
        u55b6: [ [ "🈺" ], 12, 1 ],
        u6307: [ [ "🈯", "🈯️" ], 4, 11 ],
        u6708: [ [ "🈷", "🈷️" ], 10, 11 ],
        u6709: [ [ "🈶" ], 9, 11 ],
        u6e80: [ [ "🈵" ], 8, 11 ],
        u7121: [ [ "🈚", "🈚️" ], 3, 11 ],
        u7533: [ [ "🈸" ], 11, 11 ],
        u7981: [ [ "🈲" ], 5, 11 ],
        u7a7a: [ [ "🈳" ], 6, 11 ],
        umbrella: [ [ "☔", "☔️" ], 34, 21 ],
        unamused: [ [ "😒" ], 30, 24 ],
        underage: [ [ "🔞" ], 27, 28 ],
        unlock: [ [ "🔓" ], 16, 28 ],
        up: [ [ "🆙" ], 5, 3 ],
        v: [ [ "✌", "✌️" ], 35, 18 ],
        vertical_traffic_light: [ [ "🚦" ], 9, 32 ],
        vhs: [ [ "📼" ], 28, 24 ],
        vibration_mode: [ [ "📳" ], 28, 16 ],
        video_camera: [ [ "📹" ], 28, 21 ],
        video_game: [ [ "🎮" ], 17, 7 ],
        violin: [ [ "🎻" ], 3, 17 ],
        virgo: [ [ "♍", "♍️" ], 1, 34 ],
        volcano: [ [ "🌋" ], 3, 12 ],
        vs: [ [ "🆚" ], 5, 4 ],
        walking: [ [ "🚶" ], 33, 7 ],
        waning_crescent_moon: [ [ "🌘" ], 13, 3 ],
        waning_gibbous_moon: [ [ "🌖" ], 13, 1 ],
        warning: [ [ "⚠", "⚠️" ], 16, 34 ],
        watch: [ [ "⌚", "⌚️" ], 26, 33 ],
        water_buffalo: [ [ "🐃" ], 19, 8 ],
        watermelon: [ [ "🍉" ], 14, 9 ],
        wave: [ [ "👋" ], 17, 21 ],
        wavy_dash: [ [ "〰", "〰️" ], 19, 35 ],
        waxing_crescent_moon: [ [ "🌒" ], 10, 12 ],
        wc: [ [ "🚾" ], 33, 15 ],
        weary: [ [ "😩" ], 17, 30 ],
        wedding: [ [ "💒" ], 26, 22 ],
        whale: [ [ "🐳" ], 20, 17 ],
        whale2: [ [ "🐋" ], 19, 16 ],
        wheelchair: [ [ "♿", "♿️" ], 14, 34 ],
        white_check_mark: [ [ "✅" ], 33, 34 ],
        white_circle: [ [ "⚪", "⚪️" ], 18, 34 ],
        white_flower: [ [ "💮" ], 27, 2 ],
        white_large_square: [ [ "⬜", "⬜️" ], 16, 35 ],
        white_medium_small_square: [ [ "◽", "◽️" ], 34, 15 ],
        white_medium_square: [ [ "◻", "◻️" ], 34, 13 ],
        white_small_square: [ [ "▫", "▫️" ], 34, 10 ],
        white_square_button: [ [ "🔳" ], 29, 19 ],
        wind_chime: [ [ "🎐" ], 6, 16 ],
        wine_glass: [ [ "🍷" ], 11, 15 ],
        wink: [ [ "😉" ], 30, 15 ],
        wolf: [ [ "🐺" ], 4, 20 ],
        woman: [ [ "👩" ], 20, 23 ],
        womans_clothes: [ [ "👚" ], 13, 22 ],
        womans_hat: [ [ "👒" ], 5, 22 ],
        womens: [ [ "🚺" ], 33, 11 ],
        worried: [ [ "😟" ], 7, 30 ],
        wrench: [ [ "🔧" ], 29, 7 ],
        x: [ [ "❌" ], 35, 28 ],
        yellow_heart: [ [ "💛" ], 5, 26 ],
        yen: [ [ "💴" ], 27, 8 ],
        yum: [ [ "😋" ], 30, 17 ],
        zap: [ [ "⚡", "⚡️" ], 17, 34 ],
        zero: [ [ "0⃣", "0️⃣" ], 10, 24 ],
        zzz: [ [ "💤" ], 14, 26 ]
    },
    custom: [ "bowtie", "feelsgood", "finnadie", "fu", "goberserk", "godmode", "hurtrealbad", "metal", "neckbeard", "octocat", "rage1", "rage2", "rage3", "rage4", "shipit", "suspect", "trollface" ]
};
